### ISSUE TITLE
remove-module should remove files of type

### ISSUE THREAD

**Issue by LaurentDardenne** [SeeminglyScience/ClassExplorer#48]
Removing the module should remove the type files loaded by import-module.
Why not use the key 'TypesToProcess' into the manifest (dependencies) ?

PS v5.1, ClassExplorer v2.3.3

**Comment by SeeminglyScience** [comment]
> Removing the module should remove the type files loaded by import-module.

Good note, I'll add some cleanup ❤️ 

> Why not use the key 'TypesToProcess' into the manifest (dependencies) ?

`PSCodeMethod`'s will throw if they are not resolvable prior to importing the root module. Also can't for format because `FormatsToProcess` is `AppendPath` rather than `PrependPath`
